config/routes.rb
JrubyRailsApp::Application.routes.draw do

  get "/" => 'home#index', :as=>"root"

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  devise_for :users

  resources :amazon_accounts do
    post "/reprice/enable" => "reprice#enable", :as=>:reprice_enable
    post "/reprice/disable" => "reprice#disable", :as=>:reprice_disable
    get "/ads/disable" => "advertizements#disable", :as=>:ads_disable
    get "refresh" => "amazon_accounts#refresh", :as=>:refresh
  end

  resources :amazon_listings, :only=>[:index] do
    #seems to be a pain the butt when javascript is off
    get "/reprice/disable" => "reprice#amazon_listing_reprice_disable", :as=>:reprice_disable
    get "/reprice/enable" => "reprice#amazon_listing_reprice_enable", :as=>:reprice_enable
  end
  resources :home, :only=>[:index]
  resources :how_it_works, :only=>[:index]
  resources :about, :only=>[:index]
  resources :privacy, :only=>[:index]
  resources :contact
  resources :setup, :only=>[:index]

  match "mws" => "pages#mws", :as=>:mws_instructions


end


app/models/amazon_account.rb
class AmazonAccount < ActiveRecord::Base

  require "amazonmws"

  validates_presence_of :merchant_id, :marketplace_id
  validates_uniqueness_of :merchant_id
  has_many :amazon_listings
  has_many :amazon_unshipped_items
  belongs_to :user

  before_save :validate_marketplace_id, :validate_merchant_id
  before_save :validate_amazon_account_credentials if Rails.env != "development"

  attr_accessible :merchant_id, :marketplace_id, :user_id, :social_ads
  attr_accessible :reprice_last_run,:get_inventory,:get_inventory_last_run

  protected

  def validate_merchant_id
    if self.merchant_id =~ /\s/
      self.errors.add :merchant_id, "Merchant id cannot contain spaces"
      false
    end
  end

  def validate_marketplace_id
    if self.marketplace_id =~ /\s/
      self.errors.add :marketplace_id, "Marketplace id cannot contain spaces"
      false
    end
  end

  def validate_amazon_account_credentials

    if merchant_id_changed? or marketplace_id_changed? or reprice_changed?

      status = true

      mws = AmazonMWS::Base.new(
          "access_key"=>::AWS_ACCESS_KEY,
          "secret_access_key"=>::AWS_SECRET_KEY,
          "merchant_id"=>merchant_id,
          "marketplace_id"=>marketplace_id
      )


      response = mws.get_report_request_count

      if response.accessors.include?("code")
        if response.code == "AccessDenied"
          Rails.logger.info "Forbidden to access #{merchant_id}"
          self.errors.add :merchant_id, "Forbidden to access to #{merchant_id}"
          status = false
        else
          Rails.logger.info "Error: #{response.code} : #{response.message}"
          self.errors.add :base, "Unable to validate store"
          status = false
        end
      end

      status
    end
  end


end

app/controllers/amazon_accounts_controller.rb
class AmazonAccountsController < ApplicationController

  def ssl_required?
    true
  end

  before_filter :authenticate_user!

  def new
    if current_user.amazon_account
      redirect_to :action=>:index and return
    end
  end

  def create

    current_user.amazon_account = AmazonAccount.create(params[:amazon_account])

    @amazon_account = current_user.amazon_account
    if @amazon_account.save
      redirect_to amazon_listings_path and return
    end
    render :action=>:new and return
  end


  def show
    @amazon_account = AmazonAccount.find(params[:id], :conditions => {:user_id=>current_user.id})
    render :new
  end

  def update
    @amazon_account = AmazonAccount.find(params[:id], :conditions => {:user_id=>current_user.id})
    @amazon_account.attributes=params[:amazon_account]
    if @amazon_account.save
      flash[:notice]="Changes saved successfully"
      redirect_to :action=>:index and return
    end
    flash[:alert]="Could not update account"
    render :action=>:new and return
  end

  def refresh
    @amazon_account = AmazonAccount.find(params[:amazon_account_id], :conditions => {:user_id=>current_user.id})
    @amazon_account.get_inventory = true
    @amazon_account.save!
    redirect_to :controller=>:amazon_listings, :action=>:index
  end

end

app/helpers/amazon_accounts_helper.rb
module AmazonAccountsHelper
end

app/views/amazon_accounts/index.html.erb
<!--==============================amazon_listings================================-->
<article class="grid_24">
  <div class="box white">
      <div class="padding">
		  <h3>Account Settings</h3>
		  <p>Here you can edit your account settings. Since there were two types of
          accounts you setup when you started, there are two buttons below, each 
		  one taking you to the corresponding settings to edit.</p>
		  <article class="grid_12 margin-bot">
          <% if current_user.amazon_account.nil? %>
              <%= link_to "Add Amazon Account Credentials", new_amazon_account_path, :class => "button", :alt => "You need to add your Amazon account details in order to use ProfitEngine", :title => "You need to add your Amazon account details in order to use ProfitEngine" %>
          <% else %>
              <%= link_to "Edit Amazon Account Credentials", amazon_account_path(current_user.amazon_account), :class => "button", :alt => "Edit your Amazon account details", :title => "Edit your Amazon account details" %>
          <% end %>
         </article>
	  <article class="grid_10 margin-bot" >
          <%= link_to "Edit Profit Engine Settings", edit_user_registration_url, :class => "button", :alt => "Edit your Profit Engine settings", :title => "Edit your Profit Engine settings" %>
          </article>		
        
       
      </div>
  </div>
</article>


app/views/amazon_accounts/new.erb
<%= javascript_include_tag "jquery.tipTip" %>
<%= javascript_include_tag "accounts" %>
<%= stylesheet_link_tag "accounts"%>

<!--==============================amazon_account================================-->
<article class="grid_12">
    <div class="box white maxheight">
      <div class="padding">
        <h3>Add Your Amazon Account</h3>
        <div class="wrapper">
          <figure class="img-indent">
            <div class="contact_form">
              <%= semantic_form_for @amazon_account||AmazonAccount.new(:user_id=>current_user), :html=>{:id=>"contact_form"} do |form| %>
                  <div class="error">
                    <%= form.semantic_errors %>
                  </div>
                  <div class="field">
                    <%= form.input :merchant_id, :input_html=>{:class=>"validate[required]"}, :label => "Merchant ID*" %>
                  </div>
                  <div class="field">
                    <%= form.input :marketplace_id, :input_html => {:class => "validate[required]"}, :label => "Marketplace ID*" %>
                  </div>
                  <div class="field">
                    <%= form.input :social_ads, :input_html => {:class => "checkbox"}, :label=>raw("Social Advertizing? #{image_tag "/images/icons/help.png",
                                                                                                                                    :class=>"tooltip",
                                                                                                            :title=>"If you choose this option, you will see a button next to each inventory item that will allow you to advertize your products on most popular social networks to maximize your income.<br>We suggest you enable it now and disable later if you don't want it."}") %>
                  </div>

                      <div class="submit-button-wrapper">
                        <input class="button create" data-disable-with="Working..." id="amazon_account_submit" name="commit" type="submit" value="Submit" />
                      </div>

              <% end %>
            </div>
          </figure>
        </div>
      </div>
  </div>
</article>
  <article class="grid_12">
    <div class="box white maxheight">
      <div class="padding block">
      <h3>What Do I Do Now?</h3>
      <p>You are nearly there. Follow these steps to complete your setup.</p>
      <div class="number">
		  01</div>
		<p><%= link_to "Open a new window",
                            "https://sellercentral.amazon.com/gp/mws/registration/register.html?applicationName=#{APPLICATION_NAME}&appDevMWSAccountId=#{MWS_DEV_ID}",
                            :method =>:post,
                            :id     =>"amazon_link",
                            :target => "_blank",
                            :alt    => "https://sellercentral.amazon.com/gp/mws/registration/register.html",
                            :title  => "https://sellercentral.amazon.com/gp/mws/registration/register.html" %>
and login to Amazon with your Seller Account. <br>Follow 
                <%= link_to "this link",
                            "https://sellercentral.amazon.com/gp/mws/registration/register.html?applicationName=#{APPLICATION_NAME}&appDevMWSAccountId=#{MWS_DEV_ID}",
                            :method =>:post,
                            :id     =>"amazon_link",
                            :target => "_blank",
                            :alt    => "https://sellercentral.amazon.com/gp/mws/registration/register.html",
                            :title  => "https://sellercentral.amazon.com/gp/mws/registration/register.html" %>
                  <a id="copy_link" title="Copy to clipboard">
                  <%= image_tag "clipboard.png", :alt => "Copy to clipboard", :title => "Copy to clipboard" %>
				  </a>to a page on which you can authorize Profit Engine to access your account.</p>
				  <div class="number">
				  02</div>
				<p>Check where it says
                <em><u>"I want to use an application to access my Amazon seller account with MWS."</u></em> and then type in the following information:
                <em>Application Name:</em> <span style="color:#80a407;">
				  <b id="profit_engine_name"><%= APPLICATION_NAME %></b></span>
				  <a id="copy_name" title="Copy to clipboard">
                  <%= image_tag "clipboard.png", :alt => "Copy to clipboard", :title => "Copy to clipboard" %>
				  </a><br><em>Application's Developer Account Number:</em><span style="color:#80a407;"><b id="profit_engine_id"><%= MWS_DEV_ID %>
				  </b></span><a id="copy_number" title="Copy to clipboard">
                  <%= image_tag "clipboard.png", :alt => "Copy to clipboard", :title => "Copy to clipboard" %>
				  </a><br>
				  <a href="/images/mws/step1.png" rel="prettyPhoto" title="Type in the Application Name and the Application's Developer Account Number like this">Click to see a snapshot</a>
                </p>
         <div class="number">
				  03</div>
				<p>Agree to Amazon's service agreement.<br>
				  Record your Amazon <b><u>Merchant ID</u></b>
				and <b><u>Marketplace ID</u></b><br>
				 <a href="/images/mws/step2.png" rel="prettyPhoto" title="Agree, click next and then get your Merchant ID and Marketplace ID">Click
                to see a snapshot</a></p>
		  <div class="number">
				  04</div>
				  <p>Enter the Amazon IDs that you recorded in the form on the left side of this page</p>

      </div>
    </div>
  </article>

<script>
    $("#contact_form").validationEngine();
</script>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
    $("a[rel^='prettyPhoto']").prettyPhoto();
  });
</script>
