config/routes.rb
JrubyRailsApp::Application.routes.draw do

  get "/" => 'home#index', :as=>"root"

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  devise_for :users

  resources :amazon_accounts do
    post "/reprice/enable" => "reprice#enable", :as=>:reprice_enable
    post "/reprice/disable" => "reprice#disable", :as=>:reprice_disable
    get "/ads/disable" => "advertizements#disable", :as=>:ads_disable
    get "refresh" => "amazon_accounts#refresh", :as=>:refresh
  end

  resources :amazon_listings, :only=>[:index] do
    #seems to be a pain the butt when javascript is off
    get "/reprice/disable" => "reprice#amazon_listing_reprice_disable", :as=>:reprice_disable
    get "/reprice/enable" => "reprice#amazon_listing_reprice_enable", :as=>:reprice_enable
  end
  resources :home, :only=>[:index]
  resources :how_it_works, :only=>[:index]
  resources :about, :only=>[:index]
  resources :privacy, :only=>[:index]
  resources :contact
  resources :setup, :only=>[:index]

  match "mws" => "pages#mws", :as=>:mws_instructions


end


app/controllers/reprice_controller.rb
class RepriceController < ApplicationController

  include ActionView::Helpers::NumberHelper

  def ssl_required?
    true
  end

  before_filter :authenticate_user!

  def enable
    #make sure that i'm the owner of the account
    aws = AmazonAccount.find_by_id_and_user_id(params[:amazon_account_id], current_user.id)
    aws.reprice = true
    if !aws.save
      Rails.logger.error(aws.errors)
      render :text=>"There was an error with your account. Please contact customer service", :status => :internal_server_error and return
    end
    @listings = current_user.amazon_listings.page(params[:page]).per(10)
  end

  def disable
    amazon_account = AmazonAccount.find_by_id_and_user_id(params[:amazon_account_id], current_user.id)
    amazon_account.reprice = false
    if !amazon_account.save
      Rails.logger.error(amazon_account.errors)
      render :text=>"There was an error with your account. Please contact customer service", :status => :internal_server_error and return
    end
    @listings = current_user.amazon_listings.page(params[:page]).per(10)
  end

  def amazon_listing_reprice_enable
    @amazon_listing=current_user.amazon_listings.find(params[:amazon_listing_id])
    if !@amazon_listing.amazon_account.reprice?
      render :text=>"Amazon Account is not configured for repricing", :status => :not_found and return
    end

    @amazon_listing.reprice_enable!
    if params[:low_price_limit].present?
      @amazon_listing.amazon_listings_custom_info.low_price_limit=params[:low_price_limit]
    else
      @amazon_listing.amazon_listings_custom_info.low_price_limit=number_with_precision(@amazon_listing.price/2, :precision=>2)
    end
    @amazon_listing.amazon_listings_custom_info.save!

  end

  def amazon_listing_reprice_disable
    @amazon_listing=current_user.amazon_listings.find(params[:amazon_listing_id])
    if !@amazon_listing.amazon_account.reprice?
      render :text=>"Amazon Account is not configured for repricing", :status => :not_found and return
    end

    if @amazon_listing.reprice_enabled?
      @amazon_listing.reprice_disable!
    end
  end

end

app/views/reprice/_amazon_listing_reprice_setting.html.erb
<%

   if amazon_listing.reprice_enabled?
       link = amazon_listing_reprice_disable_url(amazon_listing, :secure=>true)
   else
       link = amazon_listing_reprice_enable_url(amazon_listing, :secure=>true)
   end
%>
<%
   if amazon_listing.amazon_account && amazon_listing.amazon_account.reprice?

%>
    <div class="amazon_listing_reprice" id=<%= "amazon_listing_reprice_#{amazon_listing.id}" %>>
      <input class="amazon_listing_checkbox"
             id="amazon_listing_checkbox_<%= amazon_listing.id %>"
             name="amazon_listing_enable"
             <%= amazon_listing.reprice_enabled? ? "checked" : "" %>
             type="checkbox"
             listing_id="<%= amazon_listing.id %>"
             href="<%= link %>"
      />
      <%= tag "input",
              :id=>"low_limit_price_#{amazon_listing.id}",
              :name=>"low_limit_price[#{amazon_listing.id}]",
              :size=>"6",
              :value=>number_with_precision(amazon_listing.amazon_listings_custom_info.try(:low_price_limit), :precision=>2),
              :class=>"low_limit_price",
              :style=>"width:30px;height:14px;padding:0 1px;margin-top:4px;font-size:10px;",
              :title=>"Enter your Minimum Price. This is the price below which you won't sell this item",
              :disabled=>!amazon_listing.reprice_enabled? ? "disabled" : nil
      %>
    </div>
<%
   else
%>

    <div class="disabled disabled-checkbox" title="Please enable global reprice using The Switch in order to reprice individual items">
      <input class="amazon_listing_checkbox disabled"
             type="checkbox" disabled/>
    </div>

<%
   end
%>

app/views/reprice/_reprice_setting.erb
<% if current_user.amazon_account %>
    <%= div_for current_user.amazon_account do %>
        <% if current_user.amazon_account.reprice? %>
            <%= link_to image_tag("on.png",
                                  :title=>"Currently ON, click to turn OFF",
                                  :alt=>"Currently ON, click to turn OFF"), amazon_account_reprice_disable_path(current_user.amazon_account), :method=>:post, :remote=>true %>
        <% else %>
            <%= link_to image_tag("off.png", :title=>"Currently OFF, click to turn ON", :alt=>"Currently OFF, click to turn ON"), amazon_account_reprice_enable_path(current_user.amazon_account), :method=>:post, :remote=>true %>
        <% end %>
    <% end %>
<% end %>

app/views/reprice/amazon_listing_reprice_disable.html.erb
Item reprice disabled

app/views/reprice/amazon_listing_reprice_disable.js.erb
<% text = render :partial => 'reprice/amazon_listing_reprice_setting', :locals=>{:amazon_listing=>@amazon_listing} %>

$("#<%="amazon_listing_reprice_#{@amazon_listing.id}"%>").replaceWith("<%= escape_javascript(text)%>");

app/views/reprice/amazon_listing_reprice_enable.js.erb
<% text = render :partial => 'reprice/amazon_listing_reprice_setting', :locals=>{:amazon_listing=>@amazon_listing} %>

$("#<%="amazon_listing_reprice_#{@amazon_listing.id}"%>").replaceWith("<%= escape_javascript(text)%>");

app/views/reprice/disable.html.erb
<%=render :partial => 'amazon_listings/listing_table', :locals => {:listings=>@listings}%>

app/views/reprice/disable.js.erb
<% text = render :partial => 'reprice/reprice_setting' %>
$("#<%=dom_id current_user.amazon_account%>").replaceWith("<%= escape_javascript(text)%>");

<% listings = render :partial => 'amazon_listings/listing_table', :locals => {:listings=>@listings} %>
$(".listing_table").html("<%= escape_javascript(listings)%>")

app/views/reprice/enable.html.erb
<%=render :partial => 'amazon_listings/listing_table', :locals => {:listings=>@listings}%>

app/views/reprice/enable.js.erb
<% text = render :partial => 'reprice/reprice_setting' %>
$("#<%=dom_id current_user.amazon_account%>").replaceWith("<%= escape_javascript(text)%>");

<% listings = render :partial => 'amazon_listings/listing_table', :locals => {:listings=>@listings} %>
$(".listing_table").html("<%= escape_javascript(listings)%>")