config/routes.rb
JrubyRailsApp::Application.routes.draw do

  get "/" => 'home#index', :as=>"root"

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  devise_for :users

  resources :amazon_accounts do
    post "/reprice/enable" => "reprice#enable", :as=>:reprice_enable
    post "/reprice/disable" => "reprice#disable", :as=>:reprice_disable
    get "/ads/disable" => "advertizements#disable", :as=>:ads_disable
    get "refresh" => "amazon_accounts#refresh", :as=>:refresh
  end

  resources :amazon_listings, :only=>[:index] do
    #seems to be a pain the butt when javascript is off
    get "/reprice/disable" => "reprice#amazon_listing_reprice_disable", :as=>:reprice_disable
    get "/reprice/enable" => "reprice#amazon_listing_reprice_enable", :as=>:reprice_enable
  end
  resources :home, :only=>[:index]
  resources :how_it_works, :only=>[:index]
  resources :about, :only=>[:index]
  resources :privacy, :only=>[:index]
  resources :contact
  resources :setup, :only=>[:index]

  match "mws" => "pages#mws", :as=>:mws_instructions


end


app/views/shared/_footer.erb
<footer>
    <div class="main">
    	<div class="fright">
        	<span style="margin-right:180px;">Hosted by<%= link_to "Revion.com", "http://www.revion.com", :title=>"Hosted by Revion.com", :target=>'_blank' %></span>Profit Engine Team &nbsp;&copy; <%=Time.now.year%> <%= link_to "Privacy Policy", privacy_index_path, :title=>'Privacy Policy', :alt=>'Privacy Policy' %>
        </div>
    	<ul class="footer-menu">
		  <li class="first <%= get_active_url_css(check_if_current_url_same_as('/') || check_if_current_url_starts_with('/home')) %>">
	        <%= link_to "Home", home_index_path, :title=>'Home', :alt=>'Home' %>
	      </li>
	       <% if user_signed_in? %>
	          <li class="<%= get_active_url_css(check_if_current_url_starts_with('/amazon_account')) %>">
	            <%= link_to "Account", amazon_accounts_path, :title=>'Account Settings', :alt=>'Account Settings' %>
	          </li>
	          <li class="<%= get_active_url_css(check_if_current_url_starts_with('/amazon_listings')) %>">
	            <%= link_to "Inventory", amazon_listings_path, :title=>'Your Listings', :alt=>'Your Listings' %>
	          </li>
	      <% else %>
	      	  <li class="<%= get_active_url_css(check_if_current_url_same_as('/how_it_works')) %>">
		        <%= link_to "How It Works", how_it_works_path, :title=>'How It Works', :alt=>'How It Works' %>
		      </li>
	          <li class="<%= get_active_url_css(check_if_current_url_same_as('/users/sign_up')) %>">
	            <%= link_to "Sign Up", new_user_registration_url, :title=>'Sign Up', :alt=>'Sign Up' %>
	          </li>
	          <li class="<%= get_active_url_css(check_if_current_url_starts_with('/users/sign_in')) %>">
	            <%= link_to "Log In", user_session_path, :title=>'Log In', :alt=>'Log In' %>
	          </li>
	      <% end %>
	
	      <li class="<%= get_active_url_css(check_if_current_url_starts_with('/about')) %>">
	        <%= link_to "About", about_index_path, :title=>'About Us', :alt=>'About Us' %>
	      </li>
	      <li class="<%= get_active_url_css(check_if_current_url_starts_with('/contact')) %>">
	        <%= link_to "Contacts", contact_index_path, :title=>'Contact Us', :alt=>'Contact Us' %>
	      </li>
        </ul>
    </div>
  <%#= render :partial => 'mobile' %>
</footer>

app/views/shared/_generic_side.erb
<!--==============================user menu================================-->
<article class="grid_12">
    <div class="box gray">
        <div class="padding">
            <h3>Additional Options</h3>
            <ul class="list-1">
               <li><div class="connect"><%= link_to "Forgot your password?", new_password_url(resource_name) %></div></li>
 		       <li><div class="connect"><%= link_to image_tag("login/facebook_32.png", :alt=>"Facebook Connect"), user_omniauth_authorize_path(:facebook) %><%= link_to "Sign up with Facebook", user_omniauth_authorize_path(:facebook) %></div></li>
 		       <li><div class="connect"><%= link_to image_tag("login/google_32.png", :alt=>"Google Connect"), user_omniauth_authorize_path(:google_apps) %><%= link_to "Sign up with Google", user_omniauth_authorize_path(:google_apps) %></div></li>
            </ul>
        </div>
    </div>
</article>

app/views/shared/_header.html.erb
<div class="main">
  <div class="wrapper p">
    <a class="logo" href="<%= root_url %>"><img src="/images/profit-engine.png"></a><span class="logo-beta">beta</span>

    <div class="login">

      <% if !user_signed_in? %>
          <div class="extra-wrap">
            Login Here
            <%= form_for(User.new, :url => session_path(User), :html => {:id => 'login-form'}) do |f| %>
                <fieldset>
                  <div class="fields">
                    <%= f.email_field :email, :class => "validate[required,custom[email]]", :onfocus => "defaultText(this, 'Email:', true)", :onblur => "defaultText(this, 'Email:', true)", :value => "Email:" %>
                    <%= f.password_field :password, :class => "validate[required]", :onfocus => "defaultText(this, 'Password:', false)", :onblur => "defaultText(this, '', false)", :value => "Password:" %>

                    <%= f.submit "Login", :id=>"submit", :class => "login-button" %>

                  </div>
                </fieldset>
                <div class="social">or login with &nbsp;&nbsp;
                  <%= link_to image_tag("login/facebook_32.png", :title=>"Facebook Connect", :size=>"20x20"), user_omniauth_authorize_path(:facebook) %>
                  <%= link_to image_tag("login/google_32.png", :title=>"Google Connect", :size=>"20x20"), user_omniauth_authorize_path(:google_apps) %>

                </div>
            <% end %>
          </div>
      <% else %>
          <div class="extra-wrap">Logged in as
            <form action="" method="post" id="login-form">

              <fieldset>

                <div class="field-username">
                  <span><%= current_user.email %></span>
                </div>
                <div class="field-pass" style="left: 0px; top: 0px; width: 80px">

                </div>
                <div class="login-button-wrapper">
                  <%= link_to('Log out', destroy_user_session_path, :id=>"submit", :class=>"login-button") %>
                </div>

              </fieldset>
            </form>
          </div>
      <% end %>
    </div>
  </div>
  <!--==============================navigation=================================-->
  <nav>
    <ul class="sf-menu">

      <li class="first <%= get_active_url_css(check_if_current_url_same_as('/') || check_if_current_url_starts_with('/home')) %>">
        <%= link_to "Home", home_index_path, :title=>'Home', :alt=>'Home' %>
      </li>
      <% if user_signed_in? %>
          <li class="<%= get_active_url_css(check_if_current_url_starts_with('/amazon_account')) %>">
            <%= link_to "Account", amazon_accounts_path, :title=>'Account Settings', :alt=>'Account Settings' %>
          </li>
          <li class="<%= get_active_url_css(check_if_current_url_starts_with('/amazon_listings')) %>">
            <%= link_to "Inventory", amazon_listings_path, :title=>'Your Listings', :alt=>'Your Listings' %>
          </li>
      <% else %>
          <li class="<%= get_active_url_css(check_if_current_url_same_as('/how_it_works')) %>">
            <%= link_to "How It Works", how_it_works_path, :title=>'How It Works', :alt=>'How It Works' %>
          </li>
          <li class="<%= get_active_url_css(check_if_current_url_same_as('/users/sign_up')) %>">
            <%= link_to "Sign Up", new_user_registration_url, :title=>'Sign Up', :alt=>'Sign Up' %>
          </li>
          <% unless check_if_current_url_same_as('/') || check_if_current_url_starts_with('/home') %>
              <li class="<%= get_active_url_css(check_if_current_url_starts_with('/users/sign_in')) %>">
                <%= link_to "Log In", user_session_path, :title=>'Log In', :alt=>'Log In' %>
              </li>
          <% end %>
      <% end %>

      <li class="<%= get_active_url_css(check_if_current_url_starts_with('/about')) %>">
        <%= link_to "About", about_index_path, :title=>'About Us', :alt=>'About Us' %>
      </li>
      <li class="<%= get_active_url_css(check_if_current_url_starts_with('/contact')) %>">
        <%= link_to "Contacts", contact_index_path, :title=>'Contact Us', :alt=>'Contact Us' %>
      </li>
    </ul>
  </nav>

</div>

<% content_for :deferred_js do %>
    <%= javascript_include_tag "seatholder.min" %>
<% end %>

app/views/shared/_mobile.erb
<%#= link_to "View full site", url_for(:full_site => 1) %>
<%#= link_to "View mobile site", url_for(:mobile_site => 1) %>

app/views/shared/_sign_in_out_box.html.erb
<% if !user_signed_in? %>

    <div class="extra-wrap">
      Login Here
      <%= form_for(User.new, :url => session_path(User), :html => {:id => 'login-form'}) do |f| %>
          <fieldset>
            <div class="field-username">
              <%= f.email_field :email, :class => 'text-input', :default=>"Email:", :onFocus=>"if(this.value=='Email:'){this.value=''}", :onBlur=>"if(this.value==''){this.value='Email:'}", :style=>"left: 0px; top: 0px; width: 80px", :value => 'Email:', :type=> 'text' %>
            </div>
            <div class="field-pass">
              <%= f.password_field :password, :class => 'password-input', :default=>"Password:", :onFocus=>"this.type='password';if(this.value=='Password:'){this.value=''}", :onBlur=>"if(this.value==''){this.type='text';this.value='Password:'}", :style=>"left: 0px; top: 0px; width: 80px", :value => 'Password:', :type=>'text' %>
            </div>
            <div class="login-button-wrapper">
              <%= link_to 'Login', "#", :id=>"submit", :class=>"login-button", :onclick=>"jQuery('#login-form').submit(); return false;" %>
            </div>

          </fieldset>
      <% end %>
    </div>

<% else %>
    <div class="extra-wrap">Logged in as
      <form action="" method="post" id="login-form">

        <fieldset>

          <div class="field-username">
            <span><%= current_user.email %></span>
          </div>
          <div class="field-pass" style="left: 0px; top: 0px; width: 80px">

          </div>
          <div class="login-button-wrapper">
            <%= link_to('Log out', destroy_user_session_path, :id=>"submit", :class=>"login-button") %>
          </div>

        </fieldset>
      </form>
    </div>
<% end %>

app/views/shared/_social.html.erb
<%- content_for :deferred_js do -%>
    <div id="fb-root"></div>
    <script>
        window.fbAsyncInit = function() {
            FB.init({appId: "<%=FACEBOOK_APP_ID%>", status: true, cookie: true,
                xfbml: true});
        };
        (function() {
            var e = document.createElement('script');
            e.async = true;
            e.src = document.location.protocol +
                    '//connect.facebook.net/en_US/all.js';
            document.getElementById('fb-root').appendChild(e);
        }());
    </script>

    <script type="text/javascript">
        (function() {
            var po = document.createElement('script');
            po.type = 'text/javascript';
            po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(po, s);
        })();
    </script>

    <script src="http://platform.linkedin.com/in.js" type="text/javascript"></script>

    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e5934922658ed79"></script>
<% end %>

app/views/shared/_user_menu.erb
<!--==============================user menu================================-->
<article class="grid_5">
    <div class="box green maxheight">
        <div class="padding">
            <h3>Features</h3>
            <ul class="list-1">
            	<li><div><%= link_to "Inventory", amazon_listings_url(:secure=>true) %></div></li>
            	<li><div><%= link_to "Account", amazon_accounts_url(:secure=>true) %></div></li>
            	<li><%= link_to('Log Out', destroy_user_session_url(:secure=>true)) %></li>
            </ul>
        </div>
    </div>
</article>